

package Interfaz;
import Controladora.Controladora;
public class i_cancelar_operacion extends javax.swing.JFrame {
    Controladora Control;
    
    
    
    public i_cancelar_operacion(Controladora ctrl) {
        Control=ctrl;
    }
    
    public void MostrarCancelar(){
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        this.Etiqueta.setText("Su operacion ha sido cancelada");
       this.textmonto.setEnabled(false);
    }
    
     public void i_cancelar_operacion_retiro(double mont) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
         this.Etiqueta.setText("Su operacion ha sido cancelada, retire su dinero.");
         String m = Double.toString(mont);
          
         this.textmonto.setText(m);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Etiqueta = new javax.swing.JLabel();
        BotonCancelarOperacion = new javax.swing.JButton();
        textmonto = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Etiqueta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Etiqueta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancelar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 0, 0))); // NOI18N

        BotonCancelarOperacion.setText("Continuar");
        BotonCancelarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarOperacionActionPerformed(evt);
            }
        });

        textmonto.setEditable(false);
        textmonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textmontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Etiqueta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonCancelarOperacion)
                        .addGap(163, 163, 163)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(BotonCancelarOperacion))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancelarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarOperacionActionPerformed
      Control.Inicio(false);
        dispose();
    }//GEN-LAST:event_BotonCancelarOperacionActionPerformed

    private void textmontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textmontoActionPerformed
     
    }//GEN-LAST:event_textmontoActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelarOperacion;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textmonto;
    // End of variables declaration//GEN-END:variables
}
